<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <EnableDefaultItems>false</EnableDefaultItems>
    <AssemblyName>MiscSnippets</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ApplicationDefinition Include="MyApp.xaml" />
  </ItemGroup>

  <ItemGroup>
    <Page Include="SampleViewer.xaml" />
    <Page Include="BaselineAlignmentExample.xaml" />
    <Page Include="FigureLengthExample.xaml" />
    <Page Include="TextEffectTargetExample.xaml" />
    <Page Include="LineStackingStrategyExample.xaml" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="MyApp.xaml.cs">
      <DependentUpon>MyApp.xaml</DependentUpon>
    </Compile>
    <Compile Include="SampleViewer.xaml.cs">
      <DependentUpon>SampleViewer.xaml</DependentUpon>
    </Compile>
    <Compile Include="FigureLengthExample.xaml.cs">
      <DependentUpon>FigureLengthExample.xaml</DependentUpon>
    </Compile>
    <Compile Include="TextEffectTargetExample.xaml.cs">
      <DependentUpon>TextEffectTargetExample.xaml</DependentUpon>
    </Compile>
  </ItemGroup>

</Project>
