<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <GenerateDependencyFile>false</GenerateDependencyFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Snippet.csproj" AdditionalProperties="SnippetSource=ToUInt16\touint16_1.cs;SnippetAssemblyName=ToUInt16_1" />
    <ProjectReference Include="..\Snippet.csproj" AdditionalProperties="SnippetSource=ToUInt16\touint16_2.cs;SnippetAssemblyName=ToUInt16_2" />
    <ProjectReference Include="..\Snippet.csproj" AdditionalProperties="SnippetSource=ToUInt16\touint16_3.cs;SnippetAssemblyName=ToUInt16_3" />
    <ProjectReference Include="..\Snippet.csproj" AdditionalProperties="SnippetSource=ToUInt16\touint16_4.cs;SnippetAssemblyName=ToUInt16_4" />
  </ItemGroup>

</Project>
