<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <EnableDefaultItems>false</EnableDefaultItems>
    <RootNamespace>Microsoft.Samples.Animation.AnimatingWithStoryboards</RootNamespace>
    <AssemblyName>AnimatingWithStoryboards_csharp</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ApplicationDefinition Include="MyApp.xaml" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="MyApp.xaml.cs">
      <DependentUpon>MyApp.xaml</DependentUpon>
    </Compile>
    <Compile Include="StoryboardExample.cs" />
    <Compile Include="ControlStoryboardExample.cs" />
    <Compile Include="FrameworkContentElementControlStoryboardExample.cs" />
    <Compile Include="FrameworkContentElementStoryboardWithHandoffBehaviorExample.cs" />
    <Compile Include="FrameworkContentElementStoryboardExample.cs" />
    <Compile Include="ControlTemplateStoryboardExample.cs" />
    <Compile Include="SampleViewer.cs" />
    <Compile Include="ScopeExample.cs" />
    <Compile Include="MultipleNameScopesExample.cs" />
    <Compile Include="FrameworkElementStoryboardHandoffBehaviorExample.cs" />
    <Compile Include="SeekExample.cs" />
    <Compile Include="FrameworkContentElementSeekExample.cs" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="App.ico" />
  </ItemGroup>

</Project>
