name: Close issues
description: Close issues based on label.
resource: repository
where:
configuration:
    resourceManagementConfiguration:
        eventResponderTasks:              
          - description: Close issues labeled 'code-of-conduct'
            if:
              - payloadType: Issues
              - hasLabel:
                  label: code-of-conduct
            then:
              - closeIssue
