name: GitOps.PullRequestIssueManagement
description: Label community PRs
resource: repository

configuration:
  resourceManagementConfiguration:
    eventResponderTasks:
      - if:
        - payloadType: Pull_Request
        - isAction:
            action: Opened
        - and:
          - not:
              activitySenderHasPermission:
                permission: Admin
          - not:
              activitySenderHasPermission:
                permission: Write
          - not:
              activitySenderHasPermission:
                permission: Write
          - not:
              isActivitySender:
                user: github-actions[bot]
                issueAuthor: False
          - not:
              isActivitySender:
                user: dotnet-maestro[bot]
                issueAuthor: False
          - not:
              isActivitySender:
                user: dotnet-maestro-bot[bot]
                issueAuthor: False
          - not:
              isActivitySender:
                user: dotnet-maestro-bot
                issueAuthor: False
          - not:
              isActivitySender:
                user: dotnet-maestro
                issueAuthor: False
          - not:
              isActivitySender:
                user: github-actions
                issueAuthor: False
        then:
        - addLabel:
            label: community-contribution
        description: Label community PRs
