name: GitOps.PullRequestIssueManagement
description: GitOps.PullRequestIssueManagement primitive
resource: repository

configuration:
  resourceManagementConfiguration:
    eventResponderTasks:
      - description: Close PRs that modify files whose "source of truth" is not in this repo.
        if:
          - payloadType: Pull_Request
          - isAction:
              action: Opened
          - or:
              - filesMatchPattern:
                  pattern: xml/Microsoft.Extensions*/*
                    # TODO - These files do use this repo as source-of-truth - how to exclude them?
                    # - xml/Microsoft.Extensions.FileSystemGlobbing/*
                    # - xml/Microsoft.Extensions.FileSystemGlobbing.Abstractions/*
                    # - xml/Microsoft.Extensions.FileSystemGlobbing.Internal*/*
              - filesMatchPattern:
                  pattern: xml/System.Composition/*
              - filesMatchPattern:
                  pattern: xml/System.Formats.Cbor/*
              - filesMatchPattern:
                  pattern: xml/System.Formats.Nrbf/*
              - filesMatchPattern:
                  pattern: xml/System.Net.ServerSentEvents/*
              - filesMatchPattern:
                  pattern: xml/System.Numerics.Tensors/*
              - filesMatchPattern:
                  pattern: xml/System.Speech/*
              - filesMatchPattern:
                  pattern: xml/System.Runtime.Serialization/ISerializationCodeDomSurrogateProvider.xml
              - filesMatchPattern:
                  pattern: xml/System.Runtime.Serialization/ImportOptions.xml
              - filesMatchPattern:
                  pattern: xml/System.Runtime.Serialization/XsdDataContractExporter.xml
        then:
          - addReply:
              reply: >-
                @${issueAuthor} - This PR edits one or more files whose 'source of truth' for documentation is not in this repo. To see which files are affected, look in the .github/policies/disallow-edits.yml file. Please make documentation updates for these assemblies in the /// comments in the source repo (either dotnet/runtime or dotnet/extensions) instead.
          - if:
              - or:
                  - activitySenderHasPermission:
                      permission: None
                  - activitySenderHasPermission:
                       permission: Read
            then:
              - closePullRequest
