name: GitOps.PullRequestIssueManagement
description: GitOps.PullRequestIssueManagement primitive
resource: repository

configuration:
  resourceManagementConfiguration:
    eventResponderTasks:
      - description: Close PRs that modify files whose "source of truth" is not in this repo.
        if:
          - payloadType: Pull_Request
          - isAction:
              action: Opened
          - or:
              - filesMatchPattern:
                  pattern: xml/Microsoft.Extensions*/*
                  matchAny: true
                  excludedFiles:
                    - xml/Microsoft.Extensions.FileSystemGlobbing/*
                    - xml/Microsoft.Extensions.FileSystemGlobbing.Abstractions/*
                    - xml/Microsoft.Extensions.FileSystemGlobbing.Internal*/*
              - filesMatchPattern:
                  matchAny: true
                  pattern: xml/System.Composition/*
              - filesMatchPattern:
                  matchAny: true
                  pattern: xml/System.Formats.Cbor/*
              - filesMatchPattern:
                  matchAny: true
                  pattern: xml/System.Formats.Nrbf/*
              - filesMatchPattern:
                  matchAny: true
                  pattern: xml/System.Net.ServerSentEvents/*
              - filesMatchPattern:
                  matchAny: true
                  pattern: xml/System.Numerics.Tensors/*
              - filesMatchPattern:
                  matchAny: true
                  pattern: xml/System.Speech/*
              - filesMatchPattern:
                  matchAny: true
                  pattern: xml/System.Runtime.Serialization/ISerializationCodeDomSurrogateProvider.xml
              - filesMatchPattern:
                  matchAny: true
                  pattern: xml/System.Runtime.Serialization/ImportOptions.xml
              - filesMatchPattern:
                  matchAny: true
                  pattern: xml/System.Runtime.Serialization/XsdDataContractExporter.xml
        then:
            - addReply:
                reply: >-
                  @${issueAuthor} - This PR edits one or more files whose 'source of truth' for documentation is not in this repo. Please make documentation updates in the /// comments in the dotnet/runtime repo (or dotnet/extensions repo) instead.
            - if:
                - or:
                    - activitySenderHasPermission:
                        permission: None
                    - activitySenderHasPermission:
                        permission: Read
              then:
                - closePullRequest
