name: GitOps.PullRequestIssueManagement
description: GitOps.PullRequestIssueManagement primitive
resource: repository

configuration:
    resourceManagementConfiguration:
        eventResponderTasks:
            - description: Close PRs that modify files whose "source of truth" is not in this repo.
              if:
                  - payloadType: Pull_Request
                  - isAction:
                        action: Opened
                  - or:
                        - includesModifiedFiles:
                              files:
                                  - xml/Microsoft.Extensions*/*
                              excludedFiles:
                                  # These files use this repo as source-of-truth.
                                  - xml/Microsoft.Extensions.FileSystemGlobbing/*
                                  - xml/Microsoft.Extensions.FileSystemGlobbing.Abstractions/*
                                  - xml/Microsoft.Extensions.FileSystemGlobbing.Internal*/*
                        - includesModifiedFiles:
                              files:
                                  - xml/System.Composition
                        - includesModifiedFiles:
                              files:
                                  - xml/System.Formats.Cbor
                        - includesModifiedFiles:
                              files:
                                  - xml/System.Formats.Nrbf
                        - includesModifiedFiles:
                              files:
                                  - xml/System.Net.ServerSentEvents
                        - includesModifiedFiles:
                              files:
                                  - xml/System.Numerics.Tensors
                        - includesModifiedFiles:
                              files:
                                  - xml/System.Speech
                        - includesModifiedFile:
                              file: xml/System.Runtime.Serialization/ISerializationCodeDomSurrogateProvider.xml
                        - includesModifiedFile:
                              file: xml/System.Runtime.Serialization/ImportOptions.xml
                        - includesModifiedFile:
                              file: xml/System.Runtime.Serialization/XsdDataContractExporter.xml
              then:
                  - addReply:
                        reply: >-
                            Hello @${issueAuthor},

                            This PR will be closed because it edits files whose 'source of truth' is not in the repo.
