id: label.issues
name: GitOps.IssueManagement
description: Management logic around issues
owner:
resource: repository
disabled: false
where:
configuration:
    resourceManagementConfiguration:

        eventResponderTasks:

            - description: >-
                Remove the "needs-area-label" label when an area label is added to an issue or PR.
              if:
                - or:
                  - payloadType: Issues
                  - payloadType: Pull_Request

                - or:
                  - labelAdded:
                      label: 'area-Meta'
                  - labelAdded:
                      label: 'area-Extensions-Logging-AzureAppServices'
                  - labelAdded:
                      label: 'area-System.Security'
                  - labelAdded:
                      label: 'area-System.Drawing'
                  - labelAdded:
                      label: 'area-System.Diagnostics.Tracing'
                  - labelAdded:
                      label: 'area-System.Globalization'
                  - labelAdded:
                      label: 'area-System.Linq.Parallel'
                  - labelAdded:
                      label: 'area-System.Resources'
                  - labelAdded:
                      label: 'area-System.Text.Encoding'
                  - labelAdded:
                      label: 'area-System.Text.Encodings.Web'
                  - labelAdded:
                      label: 'area-System.Threading.Channels'
                  - labelAdded:
                      label: 'area-System.Threading.Tasks'
                  - labelAdded:
                      label: 'area-DependencyModel'
                  - labelAdded:
                      label: 'area-System.Text.RegularExpressions'
                  - labelAdded:
                      label: 'area-System.Collections'
                  - labelAdded:
                      label: 'area-System.Linq'
                  - labelAdded:
                      label: 'area-System.Numerics.Tensors'
                  - labelAdded:
                      label: 'area-System.Buffers'
                  - labelAdded:
                      label: 'area-System.Numerics'
                  - labelAdded:
                      label: 'area-System.Runtime.Intrinsics'
                  - labelAdded:
                      label: 'area-System.CodeDom'
                  - labelAdded:
                      label: 'area-System.Xml'
                  - labelAdded:
                      label: 'area-System.Runtime'
                  - labelAdded:
                      label: 'area-System.Dynamic.Runtime'
                  - labelAdded:
                      label: 'area-System.Linq.Expressions'
                  - labelAdded:
                      label: 'area-System.ComponentModel'
                  - labelAdded:
                      label: 'area-System.Configuration'
                  - labelAdded:
                      label: 'area-System.ComponentModel.Composition'
                  - labelAdded:
                      label: 'area-System.Composition'
                  - labelAdded:
                      label: 'area-System.Net'
                  - labelAdded:
                      label: 'area-System.Net.Http'
                  - labelAdded:
                      label: 'area-System.Net.Security'
                  - labelAdded:
                      label: 'area-System.Net.Sockets'
                  - labelAdded:
                      label: 'area-System.Diagnostics'
                  - labelAdded:
                      label: 'area-System.Data'
                  - labelAdded:
                      label: 'area-System.Data.OleDB'
                  - labelAdded:
                      label: 'area-System.Data.Odbc'
                  - labelAdded:
                      label: 'area-System.Data.SqlClient'
                  - labelAdded:
                      label: 'area-System.ComponentModel.DataAnnotations'
                  - labelAdded:
                      label: 'area-Extensions-AI'
                  - labelAdded:
                      label: 'area-Extensions-AI-Evaluation'
                  - labelAdded:
                      label: 'area-Extensions-Caching'
                  - labelAdded:
                      label: 'area-Extensions-DependencyInjection'
                  - labelAdded:
                      label: 'area-Extensions-Hosting'
                  - labelAdded:
                      label: 'area-Extensions-Primitives'
                  - labelAdded:
                      label: 'area-Extensions-Configuration'
                  - labelAdded:
                      label: 'area-Extensions-FileSystem'
                  - labelAdded:
                      label: 'area-Extensions-HttpClientFactory'
                  - labelAdded:
                      label: 'area-Extensions-Logging'
                  - labelAdded:
                      label: 'area-Extensions-Options'
                  - labelAdded:
                      label: 'area-System.Net.Quic'
                  - labelAdded:
                      label: 'area-System.Formats.Cbor'
                  - labelAdded:
                      label: 'area-System.Formats.Asn1'
                  - labelAdded:
                      label: 'area-System.Text.Json'
                  - labelAdded:
                      label: 'area-System.Memory'
                  - labelAdded:
                      label: 'area-System.Diagnostics.Activity'
                  - labelAdded:
                      label: 'area-System.IO'
                  - labelAdded:
                      label: 'area-System.Diagnostics.Process'
                  - labelAdded:
                      label: 'area-System.Console'
                  - labelAdded:
                      label: 'area-System.IO.Compression'
                  - labelAdded:
                      label: 'area-WPF'

              then:
                - removeLabel: 'needs-area-label'
