id:
name: GitOps.PullRequestIssueManagement
description: GitOps.PullRequestIssueManagement primitive
owner:
resource: repository
disabled: false
where:
configuration:
  resourceManagementConfiguration:
    eventResponderTasks:
    - if:
      - payloadType: Pull_Request
      - isActivitySender:
          user: dotnet-policy-service
          issueAuthor: False
      then:
      - addLabel:
          label: ':octocat: auto-merge'
      triggerOnOwnActions: true
      description: Label PRs from Dotnet Policy Service
