name: GitOps.PullRequestIssueManagement
description: Schedule a daily PR from main to live
resource: repository

configuration:
  resourceManagementConfiguration:
    scheduledSearches:
      - frequencies:
          - daily:
              time: 08:0
        filters: []
        actions:
          - createPullRequest:
              head: main
              base: live
              title: Merge main into live
              body: Please don't squash-merge this PR.
        description: Push to live branch (publish)

