<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <GenerateDependencyFile>false</GenerateDependencyFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Snippet.csproj" AdditionalProperties="SnippetSource=ToUInt64\touint64_1.cs;SnippetAssemblyName=ToUInt64_1" />
    <ProjectReference Include="..\Snippet.csproj" AdditionalProperties="SnippetSource=ToUInt64\touint64_2.cs;SnippetAssemblyName=ToUInt64_2" />
    <ProjectReference Include="..\Snippet.csproj" AdditionalProperties="SnippetSource=ToUInt64\touint64_3.cs;SnippetAssemblyName=ToUInt64_3" />
    <ProjectReference Include="..\Snippet.csproj" AdditionalProperties="SnippetSource=ToUInt64\touint64_4.cs;SnippetAssemblyName=ToUInt64_4" />
  </ItemGroup>

</Project>
