<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <EnableDefaultItems>false</EnableDefaultItems>
    <RootNamespace>Microsoft.Samples.BrushExamples</RootNamespace>
    <AssemblyName>BrushExamples</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ApplicationDefinition Include="MyApp.xaml" />
  </ItemGroup>

  <ItemGroup>
    <Page Include="SampleViewer.xaml" />
    <Page Include="SolidColorBrushExample.xaml" />
    <Page Include="OpacityExample.xaml" />
    <Page Include="SolidColorBrushAnimationExample.xaml" />
    <Page Include="ImageBrushExample.xaml" />
    <Page Include="DrawingBrushExample.xaml" />
    <Page Include="VisualBrushExample.xaml" />
    <Page Include="StretchExample.xaml" />
    <Page Include="StretchIllustration.xaml" />
    <Page Include="AlignmentExample.xaml" />
    <Page Include="TileIllustration.xaml" />
    <Page Include="TilingExample.xaml" />
    <Page Include="TileSizeExample.xaml" />
    <Page Include="TileSizeIllustration.xaml" />
    <Page Include="ViewboxIllustration.xaml" />
    <Page Include="ViewboxIllustration2.xaml" />
    <Page Include="ViewboxExample.xaml" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="SampleViewer.xaml.cs">
      <DependentUpon>SampleViewer.xaml</DependentUpon>
    </Compile>
    <Compile Include="MyApp.xaml.cs">
      <DependentUpon>MyApp.xaml</DependentUpon>
    </Compile>
    <Compile Include="SolidColorBrushExample.xaml.cs">
      <DependentUpon>SolidColorBrushExample.xaml</DependentUpon>
    </Compile>
    <Compile Include="OpacityExample.xaml.cs">
      <DependentUpon>OpacityExample.xaml</DependentUpon>
    </Compile>
    <Compile Include="SolidColorBrushAnimationExample.xaml.cs">
      <DependentUpon>SolidColorBrushAnimationExample.xaml</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="App.ico" />
    <Resource Include="sampleImages\*.*" />
  </ItemGroup>

</Project>
