<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <EnableDefaultItems>false</EnableDefaultItems>
    <AssemblyName>SDKSample</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="StackPanel_Ovw_Sample4.cs" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="smiley_stackpanel.PNG">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
