revision: 1
schema-version: 1
owner-ms-alias: adegeo

config:
  DocMetadata:
    Headers:
      - ["---", "#### "]

    ParserRegex: "^\\* (.*): (.*)$"


issues:

  reopened:

    # Remove won't fix label
    - labels-remove: ["won't fix"]

  closed:

    # Issue closed, remove in-progress label
    - labels-remove: ["in-progress"]

pull_request:

  reopened: opened

  opened:

    # Set default sprint for new PRs
    - milestone-set: "![sprint]"
