revision: 1
schema-version: 1
owner-ms-alias: adegeo

config:
  DocMetadata:
    Headers:
      - ["---", "#### "]

    ParserRegex: "^\\* (.*): (.*)$"


issues:

  opened:
    # New issue opened, add Not Triaged  
    - labels-add: [":watch: Not Triaged"]

  reopened:

    # Remove won't fix label
    - labels-remove: ["won't fix"]

  closed:

    # Issue closed, remove in-progress and not triaged labels
    - labels-remove: ["in-progress", ":watch: Not Triaged"]

pull_request:

  reopened: opened

  opened:

    # Set default sprint for new PRs
    - milestone-set: "![sprint]"
