<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <EnableDefaultItems>false</EnableDefaultItems>
    <AssemblyName>FreezableSample_csharp</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="freezablesample.cs" />
  </ItemGroup>

</Project>
