<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <EnableDefaultItems>false</EnableDefaultItems>
    <RootNamespace>CSharp</RootNamespace>
    <AssemblyName>CSharp</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ApplicationDefinition Include="App.xaml" />
  </ItemGroup>

  <ItemGroup>
    <Page Include="Show2Window.xaml" />
    <Page Include="Show3Window.xaml" />
    <Page Include="Show4Window.xaml" />
    <Page Include="Show5Window.xaml" />
    <Page Include="Show6Window.xaml" />
    <Page Include="MainWindow.xaml" />
    <Page Include="Show1Window.xaml" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Show2Window.xaml.cs">
      <DependentUpon>Show2Window.xaml</DependentUpon>
    </Compile>
    <Compile Include="Show3Window.xaml.cs">
      <DependentUpon>Show3Window.xaml</DependentUpon>
    </Compile>
    <Compile Include="Show4Window.xaml.cs">
      <DependentUpon>Show4Window.xaml</DependentUpon>
    </Compile>
    <Compile Include="Show5Window.xaml.cs">
      <DependentUpon>Show5Window.xaml</DependentUpon>
    </Compile>
    <Compile Include="Show6Window.xaml.cs">
      <DependentUpon>Show6Window.xaml</DependentUpon>
    </Compile>
    <Compile Include="MainWindow.xaml.cs">
      <DependentUpon>MainWindow.xaml</DependentUpon>
    </Compile>
    <Compile Include="Show1Window.xaml.cs">
      <DependentUpon>Show1Window.xaml</DependentUpon>
    </Compile>
  </ItemGroup>

</Project>
