<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <EnableDefaultItems>false</EnableDefaultItems>
    <AssemblyName>TimingBehaviors_csharp</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ApplicationDefinition Include="MyApp.xaml" />
  </ItemGroup>

  <ItemGroup>
    <Page Include="SampleViewer.xaml" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="MyApp.xaml.cs">
      <DependentUpon>MyApp.xaml</DependentUpon>
    </Compile>
    <Compile Include="RotateAboutCenterExample.cs" />
    <Compile Include="SampleViewer.xaml.cs">
      <DependentUpon>SampleViewer.xaml</DependentUpon>
    </Compile>
    <Compile Include="AnimatingSizeExample.cs" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="sampleImages\*.*" />
  </ItemGroup>

</Project>
