<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableDefaultItems>false</EnableDefaultItems>
    <RootNamespace>UIAInvokePattern_snip</RootNamespace>
    <AssemblyName>UIAInvokePattern_snip</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Properties\Resources.cs">
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Include="Properties\Settings.cs">
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
    <Compile Include="UIAInvokePatternTarget.cs" />
    <Compile Include="UIAInvokePatternTarget.Designer.cs">
      <DependentUpon>UIAInvokePatternTarget.cs</DependentUpon>
    </Compile>
    <Compile Include="UIAInvokePattern_snippets.cs" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Include="UIAInvokePatternTarget.resx">
      <DependentUpon>UIAInvokePatternTarget.cs</DependentUpon>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Include="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.cs</LastGenOutput>
    </None>
  </ItemGroup>

</Project>
