<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <GenerateDependencyFile>false</GenerateDependencyFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Snippet.csproj" AdditionalProperties="SnippetSource=ToDateTime\ToDateTime1.cs;SnippetAssemblyName=ToDateTime_1" />
    <ProjectReference Include="..\Snippet.csproj" AdditionalProperties="SnippetSource=ToDateTime\ToDateTime2.cs;SnippetAssemblyName=ToDateTime_2" />
    <ProjectReference Include="..\Snippet.csproj" AdditionalProperties="SnippetSource=ToDateTime\ToDateTime3.cs;SnippetAssemblyName=ToDateTime_3" />
    <ProjectReference Include="..\Snippet.csproj" AdditionalProperties="SnippetSource=ToDateTime\todatetime4.cs;SnippetAssemblyName=ToDateTime_4" />
  </ItemGroup>

</Project>
