<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <EnableDefaultItems>false</EnableDefaultItems>
    <AssemblyName>PropertiesOvwSupport</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ApplicationDefinition Include="app.xaml" />
  </ItemGroup>

  <ItemGroup>
    <Page Include="default.xaml" />
    <Page Include="Page1.xaml" />
    <Page Include="page2.xaml" />
    <Page Include="page3.xaml" />
    <Page Include="page4.xaml" />
    <Page Include="page5.xaml" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="default.xaml.cs" />
    <Compile Include="Page1.xaml.cs" />
    <Compile Include="page3.xaml.cs">
      <DependentUpon>page3.xaml</DependentUpon>
    </Compile>
    <Compile Include="page4.xaml.cs">
      <DependentUpon>page4.xaml</DependentUpon>
    </Compile>
    <Compile Include="page5.xaml.cs">
      <DependentUpon>page5.xaml</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <Content Include="wavy.JPG">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
