<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <EnableDefaultItems>false</EnableDefaultItems>
    <AssemblyName>ResourceMerge</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ApplicationDefinition Include="app.xaml">
      <Generator>MSBuild:Compile</Generator>
    </ApplicationDefinition>
  </ItemGroup>

  <ItemGroup>
    <Page Include="default.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>

  <ItemGroup>
    <Compile Include="default.xaml.cs" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="myresourcedictionary.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Resource>
    <Resource Include="myresourcedictionary2.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Resource>
  </ItemGroup>

</Project>
