<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <GenerateDependencyFile>false</GenerateDependencyFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Snippet.csproj" AdditionalProperties="SnippetSource=ToInt64\toint64_1.cs;SnippetAssemblyName=ToInt64_1" />
    <ProjectReference Include="..\Snippet.csproj" AdditionalProperties="SnippetSource=ToInt64\toint64_2.cs;SnippetAssemblyName=ToInt64_2" />
    <ProjectReference Include="..\Snippet.csproj" AdditionalProperties="SnippetSource=ToInt64\toint64_3.cs;SnippetAssemblyName=ToInt64_3" />
  </ItemGroup>

</Project>
