<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <EnableDefaultItems>false</EnableDefaultItems>
    <RootNamespace>NumericUpDownOneProject</RootNamespace>
    <AssemblyName>NumericUpDownOneProject</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ApplicationDefinition Include="app.xaml">
      <Generator>MSBuild:Compile</Generator>
    </ApplicationDefinition>
  </ItemGroup>

  <ItemGroup>
    <Page Include="themes\generic.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="Window1.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>

  <ItemGroup>
    <Compile Include="app.xaml.cs">
      <DependentUpon>app.xaml</DependentUpon>
    </Compile>
    <Compile Include="Window1.xaml.cs">
      <DependentUpon>Window1.xaml</DependentUpon>
    </Compile>
    <Compile Include="NumericUpDown.cs" />
  </ItemGroup>

</Project>
