<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <EnableDefaultItems>false</EnableDefaultItems>
    <RootNamespace>SDKSample</RootNamespace>
    <AssemblyName>SDKSample.FontSnippets</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ApplicationDefinition Include="MyApp.xaml">
      <Generator>MSBuild:Compile</Generator>
    </ApplicationDefinition>
  </ItemGroup>

  <ItemGroup>
    <Page Include="FontFamilySnippets.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="FontMapSnippets.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="FontPackageSnippets.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="FontStyleSnippets.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="pages\HomePage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="Window1.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Window1.xaml.cs">
      <DependentUpon>Window1.xaml</DependentUpon>
    </Compile>
    <Compile Include="FontFamilySnippets.xaml.cs">
      <DependentUpon>FontFamilySnippets.xaml</DependentUpon>
    </Compile>
    <Compile Include="FontMapSnippets.xaml.cs">
      <DependentUpon>FontMapSnippets.xaml</DependentUpon>
    </Compile>
    <Compile Include="FontStyleSnippets.xaml.cs">
      <DependentUpon>FontStyleSnippets.xaml</DependentUpon>
    </Compile>
    <Compile Include="FontPackageSnippets.xaml.cs">
      <DependentUpon>FontPackageSnippets.xaml</DependentUpon>
    </Compile>
    <Compile Include="pages\HomePage.xaml.cs">
      <DependentUpon>pages\HomePage.xaml</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="resources\Kooten.ttf" />
    <Resource Include="resources\Linds.ttf" />
    <Resource Include="resources\Miramo.ttf" />
    <Resource Include="resources\Miramob.ttf" />
    <Resource Include="resources\Peric.ttf" />
    <Resource Include="resources\Pericl.ttf" />
    <Resource Include="resources\Pesca.ttf" />
    <Resource Include="resources\Pescab.ttf" />
    <Resource Include="pages\Pericl.ttf" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Pericl.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
