<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <EnableDefaultItems>false</EnableDefaultItems>
    <AssemblyName>Misc Snippets</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ApplicationDefinition Include="MyApp.xaml" />
  </ItemGroup>

  <ItemGroup>
    <Page Include="BitmapEffectExample.xaml" />
    <Page Include="DrawingBrushExample.xaml" />
    <Page Include="GlyphRunExample.xaml" />
    <Page Include="ImageDrawingWithDrawingBrushExample.xaml" />
    <Page Include="SampleViewer.xaml" />
    <Page Include="DashStyleExample.xaml" />
    <Page Include="ImageDrawingExample.xaml" />
    <Page Include="DrawingImageExample.xaml" />
    <Page Include="PenStartEndLineCapExample.xaml" />
    <Page Include="PenMiterLimitExample.xaml" />
    <Page Include="DrawingGroupExample.xaml" />
    <Page Include="GeometryDrawingExample.xaml" />
    <Page Include="ClipExample.xaml" />
    <Page Include="DrawingGroupOrderingExample.xaml" />
    <Page Include="DrawingGroupGuidelineSetExample.xaml" />
    <Page Include="OpacityMaskExample.xaml" />
    <Page Include="OpacityExample.xaml" />
    <Page Include="TransformExample.xaml" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="MyApp.xaml.cs">
      <DependentUpon>MyApp.xaml</DependentUpon>
    </Compile>
    <Compile Include="SampleViewer.xaml.cs">
      <DependentUpon>SampleViewer.xaml</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="sampleImages\*.*" />
    <Resource Include="sampleMedia\*.*" />
  </ItemGroup>

</Project>
