<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <EnableDefaultItems>false</EnableDefaultItems>
    <RootNamespace>Microsoft.Samples.KeyFrameExamples</RootNamespace>
    <AssemblyName>KeyFramesSample</AssemblyName>
    <StartupObject>Microsoft.Samples.KeyFrameExamples.MyApp</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <ApplicationDefinition Include="MyApp.xaml" />
  </ItemGroup>

  <ItemGroup>
    <Page Include="InterpolationMethodsExample.xaml" />
    <Page Include="DoubleAnimationUsingKeyFramesExample.xaml" />
    <Page Include="BooleanAnimationUsingKeyFramesExample.xaml" />
    <Page Include="KeyTimesIllustration.xaml" />
    <Page Include="StringAnimationUsingKeyFramesExample.xaml" />
    <Page Include="KeyFramesIntroduction.xaml" />
    <Page Include="KeyTimesExample.xaml" />
    <Page Include="SampleViewer.xaml" />
    <Page Include="MatrixAnimationUsingKeyFramesExample.xaml" />
    <Page Include="ThicknessAnimationUsingKeyFramesExample.xaml" />
    <Page Include="PointAnimationUsingKeyFramesExample.xaml" />
    <Page Include="ColorAnimationUsingKeyFramesExample.xaml" />
    <Page Include="RectAnimationUsingKeyFramesExample.xaml" />
    <Page Include="AltDoubleAnimationUsingKeyFramesExample.xaml" />
    <Page Include="ObjectAnimationUsingKeyFramesExample.xaml" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="KeyTimesIllustration.xaml.cs">
      <DependentUpon>KeyTimesIllustration.xaml</DependentUpon>
    </Compile>
    <Compile Include="MyApp.xaml.cs">
      <DependentUpon>MyApp.xaml</DependentUpon>
    </Compile>
    <Compile Include="KeyFramesIntroduction.xaml.cs">
      <DependentUpon>KeyFramesIntroduction.xaml</DependentUpon>
    </Compile>
    <Compile Include="SampleViewer.xaml.cs">
      <DependentUpon>SampleViewer.xaml</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="App.ico" />
  </ItemGroup>

</Project>
