// <snippet100>
// <snippet101>
using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Drawing;
using System.Windows.Forms;
using AttributesDemoControlLibrary;
// </snippet101>

// This sample demonstrates using the AttributesDemoControl to log
// data from a data source. 
namespace AttributesDemoControlTest;

public class Form1 : Form
{
    BindingSource bindingSource1;
    PerformanceCounter performanceCounter1;
    Button startButton;
    Button stopButton;
    System.Timers.Timer timer1;
    ToolStripStatusLabel statusStripPanel1;
    NumericUpDown numericUpDown1;
    GroupBox groupBox1;
    GroupBox groupBox2;
    TableLayoutPanel tableLayoutPanel1;
    AttributesDemoControl attributesDemoControl1;
    Container _components;

    // This form uses an AttributesDemoControl to display a stream
    // of LogEntry objects. The data stream is generated by polling
    // a performance counter and communicating the counter values 
    // to the control with data binding.
    public Form1()
    {
        InitializeComponent();

        // Set the initial value of the threshold up/down control 
        // to the control's threshold value.
        numericUpDown1.Value =
            (decimal)(float)attributesDemoControl1.Threshold;

        // Assign the performance counter's name to the control's 
        // title text.
        attributesDemoControl1.TitleText =
            performanceCounter1.CounterName;
    }

    // This method handles the ThresholdExceeded event. It posts
    // the value that exceeded the threshold to the status strip.  
    void attributesDemoControl1_ThresholdExceeded(
        ThresholdExceededEventArgs e)
    {
        string msg = string.Format(
            "{0}: Value {1} exceeded threshold {2}",
            attributesDemoControl1.CurrentLogTime,
            e.ExceedingValue,
            e.ThresholdValue);

        ReportStatus(msg);
    }

    // <snippet110>
    // This method handles the timer's Elapsed event. It queries
    // the performance counter for the next value, packs the 
    // value in a LogEntry object, and adds the new LogEntry to
    // the list managed by the BindingSource.
    void timer1_Elapsed(
        object sender,
        System.Timers.ElapsedEventArgs e)
    {
        // Get the latest value from the performance counter.
        float val = performanceCounter1.NextValue();

        // The performance counter returns values of type float, 
        // but any type that implements the IComparable interface
        // will work.
        LogEntry<float> entry = new(val, DateTime.Now);

        // Add the new LogEntry to the BindingSource list.
        _ = bindingSource1.Add(entry);
    }
    // </snippet110>

    void numericUpDown1_ValueChanged(object sender, EventArgs e)
    {
        attributesDemoControl1.Threshold =
            (float)numericUpDown1.Value;

        string msg = string.Format(
            "Threshold changed to {0}",
            attributesDemoControl1.Threshold);

        ReportStatus(msg);
    }

    void startButton_Click(object sender, EventArgs e)
    {
        ReportStatus(DateTime.Now + ": Starting");

        timer1.Start();
    }

    void stopButton_Click(object sender, EventArgs e)
    {
        ReportStatus(DateTime.Now + ": Stopping");

        timer1.Stop();
    }

    void ReportStatus(string msg)
    {
        if (msg != null)
        {
            statusStripPanel1.Text = msg;
        }
    }

    [STAThread]
    static void Main()
    {
        Application.EnableVisualStyles();
        Application.Run(new Form1());
    }

    protected override void Dispose(bool disposing)
    {
        if (disposing && (_components != null))
        {
            _components.Dispose();
        }
        base.Dispose(disposing);
    }

    void InitializeComponent()
    {
        _components = new Container();
        bindingSource1 = new BindingSource(_components);
        performanceCounter1 = new PerformanceCounter();
        startButton = new Button();
        stopButton = new Button();
        timer1 = new System.Timers.Timer();
        statusStripPanel1 = new ToolStripStatusLabel();
        numericUpDown1 = new NumericUpDown();
        groupBox1 = new GroupBox();
        groupBox2 = new GroupBox();
        tableLayoutPanel1 = new TableLayoutPanel();
        attributesDemoControl1 = new AttributesDemoControl();
        ((ISupportInitialize)bindingSource1).BeginInit();
        performanceCounter1.BeginInit();
        timer1.BeginInit();

        numericUpDown1.BeginInit();
        groupBox1.SuspendLayout();
        groupBox2.SuspendLayout();
        tableLayoutPanel1.SuspendLayout();
        SuspendLayout();
        // 
        // performanceCounter1
        // 
        performanceCounter1.CategoryName = ".NET CLR Memory";
        performanceCounter1.CounterName = "Gen 0 heap size";
        performanceCounter1.InstanceName = "_Global_";
        // 
        // startButton
        // 
        startButton.Location = new Point(31, 25);
        startButton.Name = "startButton";
        startButton.TabIndex = 1;
        startButton.Text = "Start";
        startButton.Click += startButton_Click;
        // 
        // stopButton
        // 
        stopButton.Location = new Point(112, 25);
        stopButton.Name = "stopButton";
        stopButton.TabIndex = 2;
        stopButton.Text = "Stop";
        stopButton.Click += stopButton_Click;
        // 
        // timer1
        // 
        timer1.Interval = 1000;
        timer1.SynchronizingObject = this;
        timer1.Elapsed += timer1_Elapsed;
        // 
        // statusStripPanel1
        // 
        statusStripPanel1.BorderStyle = Border3DStyle.SunkenOuter;
        statusStripPanel1.DisplayStyle = ToolStripItemDisplayStyle.Text;
        statusStripPanel1.Name = "statusStripPanel1";
        statusStripPanel1.Text = "Ready";
        // 
        // numericUpDown1
        // 
        numericUpDown1.Location = new Point(37, 29);
        numericUpDown1.Maximum = new decimal(new int[] { 1410065408, 2, 0, 0 });
        numericUpDown1.Name = "numericUpDown1";
        numericUpDown1.TabIndex = 7;
        numericUpDown1.ValueChanged += numericUpDown1_ValueChanged;
        // 
        // groupBox1
        // 
        groupBox1.Anchor = AnchorStyles.None;
        groupBox1.Controls.Add(numericUpDown1);
        groupBox1.Location = new Point(280, 326);
        groupBox1.Name = "groupBox1";
        groupBox1.Size = new Size(200, 70);
        groupBox1.TabIndex = 13;
        groupBox1.TabStop = false;
        groupBox1.Text = "Threshold Value";
        // 
        // groupBox2
        // 
        groupBox2.Anchor = AnchorStyles.None;
        groupBox2.Controls.Add(startButton);
        groupBox2.Controls.Add(stopButton);
        groupBox2.Location = new Point(26, 327);
        groupBox2.Name = "groupBox2";
        groupBox2.Size = new Size(214, 68);
        groupBox2.TabIndex = 14;
        groupBox2.TabStop = false;
        groupBox2.Text = "Logging";
        // 
        // tableLayoutPanel1
        // 
        tableLayoutPanel1.ColumnCount = 2;
        tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
        tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
        tableLayoutPanel1.Controls.Add(groupBox2, 0, 1);
        tableLayoutPanel1.Controls.Add(groupBox1, 1, 1);
        tableLayoutPanel1.Controls.Add(attributesDemoControl1, 0, 0);
        tableLayoutPanel1.Dock = System.Windows.Forms.DockStyle.Fill;
        tableLayoutPanel1.Location = new System.Drawing.Point(0, 0);
        tableLayoutPanel1.Name = "tableLayoutPanel1";
        tableLayoutPanel1.Padding = new System.Windows.Forms.Padding(10);
        tableLayoutPanel1.RowCount = 2;
        tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 80F));
        tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 20F));
        tableLayoutPanel1.Size = new System.Drawing.Size(514, 411);
        tableLayoutPanel1.TabIndex = 15;
        // 
        // attributesDemoControl1
        // 
        tableLayoutPanel1.SetColumnSpan(attributesDemoControl1, 2);
        attributesDemoControl1.DataMember = "";
        attributesDemoControl1.DataSource = bindingSource1;
        attributesDemoControl1.Dock = DockStyle.Fill;
        attributesDemoControl1.Location = new Point(13, 13);
        attributesDemoControl1.Name = "attributesDemoControl1";
        attributesDemoControl1.Padding = new Padding(10);
        attributesDemoControl1.Size = new Size(488, 306);
        attributesDemoControl1.TabIndex = 0;
        attributesDemoControl1.Threshold = 200000F;
        attributesDemoControl1.TitleText = "TITLE";
        attributesDemoControl1.ThresholdExceeded += new ThresholdExceededEventHandler(attributesDemoControl1_ThresholdExceeded);
        // 
        // Form1
        // 
        BackColor = SystemColors.Control;
        ClientSize = new Size(514, 430);
        Controls.Add(tableLayoutPanel1);
        Font = new Font("Microsoft Sans Serif", 8.25F, FontStyle.Regular, GraphicsUnit.Point, 0);
        Name = "Form1";
        Text = "Form1";
        ((ISupportInitialize)bindingSource1).EndInit();
        performanceCounter1.EndInit();
        timer1.EndInit();
        numericUpDown1.EndInit();
        groupBox1.ResumeLayout(false);
        groupBox2.ResumeLayout(false);
        tableLayoutPanel1.ResumeLayout(false);
        ResumeLayout(false);
        PerformLayout();
    }
}
// </snippet100>
