<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <EnableDefaultItems>false</EnableDefaultItems>
    <RootNamespace>ListBoxItemStyle</RootNamespace>
    <AssemblyName>ListBoxItemStyle</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ApplicationDefinition Include="app.xaml" />
  </ItemGroup>

  <ItemGroup>
    <Page Include="Pane1.xaml" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="app.xaml.cs">
      <DependentUpon>app.xaml</DependentUpon>
    </Compile>
    <Compile Include="Pane1.xaml.cs">
      <DependentUpon>Pane1.xaml</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="App.ico" />
  </ItemGroup>

</Project>
