<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <EnableDefaultItems>false</EnableDefaultItems>
    <RootNamespace>Microsoft.Samples.GradientBrushExamples</RootNamespace>
    <AssemblyName>GradientBrushExamples</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ApplicationDefinition Include="MyApp.xaml" />
  </ItemGroup>

  <ItemGroup>
    <Page Include="SampleViewer.xaml" />
    <Page Include="LinearGradientBrushExample.xaml" />
    <Page Include="RadialGradientBrushExample.xaml" />
    <Page Include="GradientStopsExample.xaml" />
    <Page Include="GradientBrushMappingModeExample.xaml" />
    <Page Include="ColorInterpolationModeExample.xaml" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="SampleViewer.xaml.cs">
      <DependentUpon>SampleViewer.xaml</DependentUpon>
    </Compile>
    <Compile Include="MyApp.xaml.cs">
      <DependentUpon>MyApp.xaml</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="App.ico" />
    <Resource Include="sampleImages\*.*" />
  </ItemGroup>

</Project>
