<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <EnableDefaultItems>false</EnableDefaultItems>
    <RootNamespace>Microsoft.Samples.CustomControls</RootNamespace>
    <AssemblyName>ColorPicker</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ApplicationDefinition Include="MyApp.xaml">
      <Generator>MSBuild:Compile</Generator>
    </ApplicationDefinition>
  </ItemGroup>

  <ItemGroup>
    <Page Include="SampleViewer.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="ColorPickerDialog.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="Themes\generic.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>

  <ItemGroup>
    <Compile Include="MyApp.xaml.cs">
      <DependentUpon>MyApp.xaml</DependentUpon>
    </Compile>
    <Compile Include="SampleViewer.xaml.cs">
      <DependentUpon>SampleViewer.xaml</DependentUpon>
    </Compile>
    <Compile Include="ColorPicker.cs" />
    <Compile Include="SupportingClasses.cs" />
    <Compile Include="ColorPickerDialog.xaml.cs">
      <DependentUpon>ColorPickerDialog.xaml</DependentUpon>
    </Compile>
  </ItemGroup>

</Project>
