<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <EnableDefaultItems>false</EnableDefaultItems>
    <RootNamespace>SDKSample</RootNamespace>
    <AssemblyName>PerformanceSnippets</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ApplicationDefinition Include="MyApp.xaml" />
  </ItemGroup>

  <ItemGroup>
    <Page Include="BrushResource.xaml" />
    <Page Include="DynamicResource.xaml" />
    <Page Include="FlowDocument.xaml" />
    <Page Include="Hyperlink.xaml" />
    <Page Include="TestNavigation.xaml" />
    <Page Include="NewPage.xaml" />
    <Page Include="Window1.xaml" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Hyperlink.xaml.cs">
      <DependentUpon>Hyperlink.xaml</DependentUpon>
    </Compile>
    <Compile Include="TestNavigation.xaml.cs">
      <DependentUpon>TestNavigation.xaml</DependentUpon>
    </Compile>
    <Compile Include="Window1.xaml.cs">
      <DependentUpon>Window1.xaml</DependentUpon>
    </Compile>
  </ItemGroup>

</Project>
