<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <EnableDefaultItems>false</EnableDefaultItems>
    <RootNamespace>SDKSample</RootNamespace>
    <AssemblyName>PackageRead</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="PackageRead.cs" />
  </ItemGroup>

</Project>
