<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <EnableDefaultItems>false</EnableDefaultItems>
    <RootNamespace>GeometryDesigner</RootNamespace>
    <AssemblyName>GeometryDesigner</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ApplicationDefinition Include="app.xaml" />
  </ItemGroup>

  <ItemGroup>
    <Page Include="Window1.xaml" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="app.xaml.cs" />
    <Compile Include="Window1.xaml.cs" />
  </ItemGroup>

</Project>
