<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <EnableDefaultItems>false</EnableDefaultItems>
    <RootNamespace>CustomControlLibrary</RootNamespace>
    <AssemblyName>CustomControlLibrary</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Page Include="themes\Luna.NormalColor.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="themes\generic.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>

  <ItemGroup>
    <Compile Include="NumericUpDown.cs" />
    <Compile Include="NumericUpDown2.cs" />
  </ItemGroup>

</Project>
