//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.WCF.Documentation
{
    using System.Runtime.Serialization;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GreetingFault : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string MessageField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://microsoft.wcf.documentation", ConfigurationName="ISampleService")]
public interface ISampleService
{

    [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.wcf.documentation/ISampleService/SampleMethod", ReplyAction="http://microsoft.wcf.documentation/ISampleService/SampleMethodResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.WCF.Documentation.GreetingFault), Action="http://www.contoso.com/GreetingFault", Name="GreetingFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.WCF.Documentation")]
    string SampleMethod(string msg);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface ISampleServiceChannel : ISampleService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class SampleServiceClient : System.ServiceModel.ClientBase<ISampleService>, ISampleService
{
    private const string DefaultEndpointAddress = "http://localhost:8080/SampleService";
    private const string WsHttpBindingEndpointName = "WSHttpBinding_ISampleService";

    private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(string endpointConfigurationName)
    {
        if (string.Equals(endpointConfigurationName, WsHttpBindingEndpointName, System.StringComparison.Ordinal))
        {
            return new System.ServiceModel.WSHttpBinding();
        }

        throw new System.InvalidOperationException(string.Format("Could not find endpoint with name '{0}'.", endpointConfigurationName));
    }

    private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
    {
        return new System.ServiceModel.EndpointAddress(DefaultEndpointAddress);
    }

    public SampleServiceClient()
            : base(new System.ServiceModel.WSHttpBinding(), GetDefaultEndpointAddress())
    {
    }

    public SampleServiceClient(string endpointConfigurationName) :
            base(GetBindingForEndpoint(endpointConfigurationName), GetDefaultEndpointAddress())
    {
    }

    public SampleServiceClient(string endpointConfigurationName, string remoteAddress) :
            base(GetBindingForEndpoint(endpointConfigurationName), new System.ServiceModel.EndpointAddress(remoteAddress))
    {
    }

    public SampleServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(GetBindingForEndpoint(endpointConfigurationName), remoteAddress)
    {
    }

    public SampleServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
    {
    }

    public string SampleMethod(string msg)
    {
        return base.Channel.SampleMethod(msg);
    }
}
