<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <EnableDefaultItems>false</EnableDefaultItems>
    <RootNamespace>WindowIconSample</RootNamespace>
    <AssemblyName>WindowIconSample</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ApplicationDefinition Include="App.xaml" />
  </ItemGroup>

  <ItemGroup>
    <Page Include="MainWindow.xaml" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="MainWindow.xaml.cs">
      <DependentUpon>MainWindow.xaml</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="WPFIcon1.ico" />
    <Resource Include="SystemIcon.ico" />
    <Resource Include="WPFIcon2.ico" />
  </ItemGroup>

</Project>
