<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <EnableDefaultItems>false</EnableDefaultItems>
    <RootNamespace>Microsoft.Samples.Graphics.OpacityMask</RootNamespace>
    <AssemblyName>OpacityMaskingExamples</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ApplicationDefinition Include="app.xaml">
      <Generator>MSBuild:Compile</Generator>
    </ApplicationDefinition>
  </ItemGroup>

  <ItemGroup>
    <Page Include="SampleViewer.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="GradientBrushExample.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="DrawingBrushExample.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="ImageBrushExample.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="App.ico" />
    <Resource Include="sampleImages\tornedges.png" />
    <Resource Include="sampleImages\Waterlilies.jpg" />
  </ItemGroup>

</Project>
