<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <RootNamespace>CustomElementClient</RootNamespace>
    <AssemblyName>CustomElementClient</AssemblyName>
  </PropertyGroup>
</Project>