<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <EnableDefaultItems>false</EnableDefaultItems>
    <RootNamespace>DataBindingLab</RootNamespace>
    <AssemblyName>DataBindingLab</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ApplicationDefinition Include="DataBindingLabApp.xaml">
      <Generator>MSBuild:Compile</Generator>
    </ApplicationDefinition>
  </ItemGroup>

  <ItemGroup>
    <Page Include="AddProductWindow.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="MainWindow.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>

  <ItemGroup>
    <Compile Include="DataBindingLabApp.xaml.cs">
      <DependentUpon>DataBindingLabApp.xaml</DependentUpon>
    </Compile>
    <Compile Include="AddProductWindow.xaml.cs">
      <DependentUpon>AddProductWindow.xaml</DependentUpon>
    </Compile>
    <Compile Include="MainWindow.xaml.cs">
      <DependentUpon>MainWindow.xaml</DependentUpon>
    </Compile>
    <Compile Include="AuctionItem.cs" />
    <Compile Include="Bid.cs" />
    <Compile Include="DateConverter.cs" />
    <Compile Include="FutureDateRule.cs" />
    <Compile Include="SpecialFeaturesConverter.cs" />
    <Compile Include="User.cs" />
  </ItemGroup>

</Project>
