<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <EnableDefaultEmbeddedResourceItems>false</EnableDefaultEmbeddedResourceItems>
    <RootNamespace>UIAProvider</RootNamespace>
    <AssemblyName>UIAProvider</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="CustomGridItem.cs" />
    <Compile Include="Form1.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Include="Form1.Designer.cs">
      <DependentUpon>Form1.cs</DependentUpon>
    </Compile>
    <Compile Include="CustomGrid.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Include="Program.cs" />
  </ItemGroup>

</Project>
