<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <GenerateDependencyFile>false</GenerateDependencyFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Snippet.csproj" AdditionalProperties="SnippetSource=ToString\ToString.Byte1.cs;SnippetAssemblyName=ToString_Byte1" />
    <ProjectReference Include="..\Snippet.csproj" AdditionalProperties="SnippetSource=ToString\ToString_Bool1.cs;SnippetAssemblyName=ToString_Bool1" />
    <ProjectReference Include="..\Snippet.csproj" AdditionalProperties="SnippetSource=ToString\nonnumeric.cs;SnippetAssemblyName=ToString_nonnumeric" />
    <ProjectReference Include="..\Snippet.csproj" AdditionalProperties="SnippetSource=ToString\tostring1.cs;SnippetAssemblyName=ToString_1" />
    <ProjectReference Include="..\Snippet.csproj" AdditionalProperties="SnippetSource=ToString\tostring2.cs;SnippetAssemblyName=ToString_2" />
    <ProjectReference Include="..\Snippet.csproj" AdditionalProperties="SnippetSource=ToString\tostring3.cs;SnippetAssemblyName=ToString_3" />
    <ProjectReference Include="..\Snippet.csproj" AdditionalProperties="SnippetSource=ToString\tostring5.cs;SnippetAssemblyName=ToString_5" />
    <ProjectReference Include="..\Snippet.csproj" AdditionalProperties="SnippetSource=ToString\tostring6.cs;SnippetAssemblyName=ToString_6" />
    <ProjectReference Include="..\Snippet.csproj" AdditionalProperties="SnippetSource=ToString\tostring7.cs;SnippetAssemblyName=ToString_7" />
    <ProjectReference Include="..\Snippet.csproj" AdditionalProperties="SnippetSource=ToString\tostring_obj30.cs;SnippetAssemblyName=ToString_obj30" />
    <ProjectReference Include="..\Snippet.csproj" AdditionalProperties="SnippetSource=ToString\tostring_string1.cs;SnippetAssemblyName=ToString_string1" />
  </ItemGroup>

</Project>
