<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>SDKSample</RootNamespace>
    <AssemblyName>CSharp</AssemblyName>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <StartupObject>SDKSample.App</StartupObject>
  </PropertyGroup>
</Project>
