<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <EnableDefaultItems>false</EnableDefaultItems>
    <AssemblyName>AnimatedHeightExample_csharp</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ApplicationDefinition Include="app.xaml" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="AnimatedHeightExample.cs" />
    <Compile Include="app.xaml.cs">
      <DependentUpon>app.xaml</DependentUpon>
    </Compile>
  </ItemGroup>

</Project>
