<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <GenerateDependencyFile>false</GenerateDependencyFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Snippet.csproj" AdditionalProperties="SnippetSource=ToDouble\example8.cs;SnippetAssemblyName=ToDouble_example8" />
    <ProjectReference Include="..\Snippet.csproj" AdditionalProperties="SnippetSource=ToDouble\todouble.cs;SnippetAssemblyName=ToDouble" />
    <ProjectReference Include="..\Snippet.csproj" AdditionalProperties="SnippetSource=ToDouble\todouble1.cs;SnippetAssemblyName=ToDouble_1" />
  </ItemGroup>

</Project>
