<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <EnableDefaultItems>false</EnableDefaultItems>
    <AssemblyName>EffectsGallery sample</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ApplicationDefinition Include="MyApp.xaml" />
  </ItemGroup>

  <ItemGroup>
    <Page Include="SampleViewer.xaml" />
    <Page Include="AnimateEffectInGroup.xaml" />
    <Page Include="EffectInputSimpleExample.xaml" />
    <Page Include="OuterGlowSimpleExample.xaml" />
    <Page Include="OuterGlowCodeBehindExample.xaml" />
    <Page Include="OuterGlowStyleExample.xaml" />
    <Page Include="OuterGlowAnimationExample.xaml" />
    <Page Include="BlurSimpleExample.xaml" />
    <Page Include="BlurCodeBehindExample.xaml" />
    <Page Include="BlurStyleExample.xaml" />
    <Page Include="BlurAnimationExample.xaml" />
    <Page Include="DropShadowSimpleExample.xaml" />
    <Page Include="DropShadowCodeBehindExample.xaml" />
    <Page Include="DropShadowStyleExample.xaml" />
    <Page Include="DropShadowAnimationExample.xaml" />
    <Page Include="MultipleEffectExample.xaml" />
    <Page Include="MultipleEffectAnimationExample.xaml" />
    <Page Include="BevelSimpleExample.xaml" />
    <Page Include="BevelCodeBehindExample.xaml" />
    <Page Include="BevelStyleExample.xaml" />
    <Page Include="BevelAnimationExample.xaml" />
    <Page Include="EmbossSimpleExample.xaml" />
    <Page Include="EmbossCodeBehindExample.xaml" />
    <Page Include="EmbossStyleExample.xaml" />
    <Page Include="EmbossAnimationExample.xaml" />
    <Page Include="EmbossStudyAnimation.xaml" />
    <Page Include="EmbossStudyStatic.xaml" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="MyApp.xaml.cs">
      <DependentUpon>MyApp.xaml</DependentUpon>
    </Compile>
    <Compile Include="SampleViewer.xaml.cs">
      <DependentUpon>SampleViewer.xaml</DependentUpon>
    </Compile>
    <Compile Include="MultipleEffectExample.cs" />
    <Compile Include="MultipleEffectAnimationExample.cs" />
    <Compile Include="OuterGlowCodeBehindExample.xaml.cs">
      <DependentUpon>OuterGlowCodeBehindExample.xaml</DependentUpon>
    </Compile>
    <Compile Include="BlurCodeBehindExample.xaml.cs">
      <DependentUpon>BlurCodeBehindExample.xaml</DependentUpon>
    </Compile>
    <Compile Include="DropShadowCodeBehindExample.xaml.cs">
      <DependentUpon>DropShadowCodeBehindExample.xaml</DependentUpon>
    </Compile>
    <Compile Include="BevelCodeBehindExample.xaml.cs">
      <DependentUpon>BevelCodeBehindExample.xaml</DependentUpon>
    </Compile>
    <Compile Include="EmbossCodeBehindExample.xaml.cs">
      <DependentUpon>EmbossCodeBehindExample.xaml</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <Content Include="Images\*.*">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
