<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <EnableDefaultItems>false</EnableDefaultItems>
    <AssemblyName>EventOvwSupport</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ApplicationDefinition Include="app.xaml" />
  </ItemGroup>

  <ItemGroup>
    <Page Include="default.xaml" />
    <Page Include="page2.xaml" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="default.xaml.cs" />
    <Compile Include="page2.xaml.cs" />
  </ItemGroup>

</Project>
