<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <EnableDefaultItems>false</EnableDefaultItems>
    <AssemblyName>BitmapFrame</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="BitmapFrame.cs" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="tulipfarm.tif">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <None Include="app.config" />
  </ItemGroup>

</Project>
