<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <EnableDefaultItems>false</EnableDefaultItems>
    <RootNamespace>SDKSample</RootNamespace>
    <AssemblyName>CodeOnlyBinding</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="binding.cs" />
    <Compile Include="MyData.cs" />
  </ItemGroup>

</Project>
