<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableDefaultItems>false</EnableDefaultItems>
    <RootNamespace>VSMButtonTemplate</RootNamespace>
    <AssemblyName>VSMButtonTemplate</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ApplicationDefinition Include="App.xaml">
      <Generator>MSBuild:Compile</Generator>
    </ApplicationDefinition>
  </ItemGroup>

  <ItemGroup>
    <Page Include="ButtonStages.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="SkinnedButton.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="Window1.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>

  <ItemGroup>
    <Compile Include="App.xaml.cs">
      <DependentUpon>App.xaml</DependentUpon>
    </Compile>
    <Compile Include="ButtonStages.xaml.cs">
      <DependentUpon>ButtonStages.xaml</DependentUpon>
    </Compile>
    <Compile Include="ControlContracts.cs" />
    <Compile Include="SkinnedButton.xaml.cs">
      <DependentUpon>SkinnedButton.xaml</DependentUpon>
    </Compile>
    <Compile Include="Window1.xaml.cs">
      <DependentUpon>Window1.xaml</DependentUpon>
    </Compile>
  </ItemGroup>

</Project>
