<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <EnableDefaultItems>false</EnableDefaultItems>
    <RootNamespace>Microsoft.Samples.VisualBrushExamples</RootNamespace>
    <AssemblyName>VisualBrushExamples</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ApplicationDefinition Include="App.xaml" />
  </ItemGroup>

  <ItemGroup>
    <Page Include="PaintWithVideoExample.xaml" />
    <Page Include="ReflectionExample.xaml" />
    <Page Include="SampleViewer.xaml" />
    <Page Include="AutoLayoutContentExample.xaml" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="App.xaml.cs">
      <DependentUpon>App.xaml</DependentUpon>
    </Compile>
    <Compile Include="SampleViewer.xaml.cs">
      <DependentUpon>SampleViewer.xaml</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <Content Include="sampleMedia\*.*">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
