<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <AssemblyName>$(SnippetAssemblyName)</AssemblyName>
    <IntermediateOutputPath>obj\$(SnippetAssemblyName)\$(Configuration)\$(TargetFramework)\</IntermediateOutputPath>
    <OutputPath>bin\$(SnippetAssemblyName)\$(Configuration)\$(TargetFramework)\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="$(SnippetSource)" />
  </ItemGroup>

</Project>
