Example.Run();
ConcatAlphabetExample.Run();
ConcatAnimalsExample.Run();
ConcatScrambleExample.Run();
ConcatThreeStringsExample.Run();
stringConcat5.Run();
ConcatTest.Run();
ConcatArrayExample.Run();
ConcatNamesTest.Run();
